### ISSUE TITLE
Missing an ICCV2019 tracker, fdKCF.

### ISSUE THREAD

**Issue by noneUmbrella** [JudasDie/Comparision#1]
Thanks for your valuable collecting work.
To further improve this system, I find that you may missing an ICCV2019 tracker, fdKCF[1].

[1] Fast-deepKCF Without Boundary Effect

**Comment by JudasDie** [comment]
> Thanks for your valuable collecting work.
> To further improve this system, I find that you may missing an ICCV2019 tracker, fdKCF[1].
> 
> [1] Fast-deepKCF Without Boundary Effect

Thanks, I will update it later

**Comment by JudasDie** [comment]
> Thanks for your valuable collecting work.
> To further improve this system, I find that you may missing an ICCV2019 tracker, fdKCF[1].
> 
> [1] Fast-deepKCF Without Boundary Effect

fixed.
